### ISSUE TITLE
API doc?

### ISSUE THREAD

**Issue by matshj** [pyalarmdotcom/pyalarmdotcomajax#135]
Hi

I'm a Homey user and I'm going to make an attempt to make an homey app for the alarm.com but I haven't been able to find any documentation of the API.
Any one here who knows where to find it?
Regards

**Comment by elahd** [comment]
Unfortunately, there's no API doc as Alarm.com doesn't support third party access. The best you'll get is by monitoring async communication on the alarm.com website.

Alarm.com uses Ember.js, so you'll want to familiarize yourself with the [JSON:API](https://jsonapi.org/) protocol and install the [Ember Inspector](https://chromewebstore.google.com/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi) browser extension.
