### ISSUE TITLE
Question about 2FA cookie

### ISSUE THREAD

**Issue by FlyingDiver** [pyalarmdotcom/pyalarmdotcomajax#49]
I didn't see this documented anywhere.

How long is the 2FA cookie good for, and is there any way to refresh it without requiring the user to enter a new OTP?

**Comment by elahd** [comment]
I can’t say officially, but in my experience they’re valid indefinitely. I’ve never been prompted to reauthenticate. Keep in mind that every alarm.com provider is able to do their own thing, so YMMV.

**Comment by FlyingDiver** [comment]
When I posted the question, I hadn't seen that it does re-login to refresh the current tokens.  But it seems happy to keep using the original cookie.  Which is very strange, but if it works, so be it.
